spring.application.name=email-automation
spring.devtools.add-properties=false
spring.devtools.restart.enabled=false

# Apollo.io
apollo.api.key=${APOLLO_API_KEY:oqMbYpeOzwBATFaZnCGmfg}
apollo.contacts.per_company=${APOLLO_CONTACTS_PER_COMPANY:5}

# Hunter.io
hunter.api.key=${HUNTER_API_KEY:20454ac0e052369d1975c53c53316482bc2a0f77}

# ZeroBounce
zerobounce.api.key=${ZEROBOUNCE_API_KEY:971f83aca88d4444881f332d03b477b8}

# Gmail API (not yet configured)
gmail.client.id=${GMAIL_CLIENT_ID:test}
gmail.client.secret=${GMAIL_CLIENT_SECRET:test}
gmail.refresh.token=${GMAIL_REFRESH_TOKEN:test}
gmail.sender.email=${GMAIL_SENDER_EMAIL:test}

# Pipeline Config
pipeline.lookalike.limit=${PIPELINE_LOOKALIKE_LIMIT:10}
pipeline.email.subject=${PIPELINE_EMAIL_SUBJECT:test}

# Disable web server
spring.main.web-application-type=none